config/routes.rb
Rails.application.routes.draw do
  resources :quotdetails

  resources :quots

  root 'quots#index'

end

app/models/quot.rb
class Quot < ActiveRecord::Base
  has_many :quotdetails
end

app/models/quotdetail.rb
class Quotdetail < ActiveRecord::Base
  belongs_to :quot
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotdetails_controller.rb
class QuotdetailsController < ApplicationController
  before_action :set_quotdetail, only: [:show, :edit, :update, :destroy]

  # GET /quotdetails
  # GET /quotdetails.json
  def index
    @quotdetails = Quotdetail.all
  end

  # GET /quotdetails/1
  # GET /quotdetails/1.json
  def show
  end

  # GET /quotdetails/new
  def new
    @quotdetail = Quotdetail.new
  end

  # GET /quotdetails/1/edit
  def edit
  end

  # POST /quotdetails
  # POST /quotdetails.json
  def create
    @quotdetail = Quotdetail.new(quotdetail_params)

    respond_to do |format|
      if @quotdetail.save
        format.html { redirect_to @quotdetail, notice: 'Quotdetail was successfully created.' }
        format.json { render :show, status: :created, location: @quotdetail }
      else
        format.html { render :new }
        format.json { render json: @quotdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotdetails/1
  # PATCH/PUT /quotdetails/1.json
  def update
    respond_to do |format|
      if @quotdetail.update(quotdetail_params)
        format.html { redirect_to @quotdetail, notice: 'Quotdetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotdetail }
      else
        format.html { render :edit }
        format.json { render json: @quotdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotdetails/1
  # DELETE /quotdetails/1.json
  def destroy
    @quotdetail.destroy
    respond_to do |format|
      format.html { redirect_to quotdetails_url, notice: 'Quotdetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotdetail
      @quotdetail = Quotdetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotdetail_params
      params.require(:quotdetail).permit(:quot_number, :product_name, :unit_price, :unit, :quantity, :extended_price, :quot_id)
    end
end

app/controllers/quots_controller.rb
class QuotsController < ApplicationController
  before_action :set_quot, only: [:show, :edit, :update, :destroy]

  # GET /quots
  # GET /quots.json
  def index
    @quots = Quot.all
  end

  # GET /quots/1
  # GET /quots/1.json
  def show
  end

  # GET /quots/new
  def new
    @quot = Quot.new
  end

  # GET /quots/1/edit
  def edit
  end

  # POST /quots
  # POST /quots.json
  def create
    @quot = Quot.new(quot_params)

    respond_to do |format|
      if @quot.save
        format.html { redirect_to @quot, notice: 'Quot was successfully created.' }
        format.json { render :show, status: :created, location: @quot }
      else
        format.html { render :new }
        format.json { render json: @quot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quots/1
  # PATCH/PUT /quots/1.json
  def update
    respond_to do |format|
      if @quot.update(quot_params)
        format.html { redirect_to @quot, notice: 'Quot was successfully updated.' }
        format.json { render :show, status: :ok, location: @quot }
      else
        format.html { render :edit }
        format.json { render json: @quot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quots/1
  # DELETE /quots/1.json
  def destroy
    @quot.destroy
    respond_to do |format|
      format.html { redirect_to quots_url, notice: 'Quot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quot
      @quot = Quot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quot_params
      params.require(:quot).permit(:quot_number, :customer, :representative, :issued, :consumption_tax, :total_amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotdetails_helper.rb
module QuotdetailsHelper
end

app/helpers/quots_helper.rb
module QuotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quotation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotdetails/_form.html.erb
<%= form_for(@quotdetail) do |f| %>
  <% if @quotdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quotdetail.errors.count, "error") %> prohibited this quotdetail from being saved:</h2>

      <ul>
      <% @quotdetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quot_number %><br>
    <%= f.text_field :quot_number %>
  </div>
  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :unit_price %><br>
    <%= f.number_field :unit_price %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :extended_price %><br>
    <%= f.number_field :extended_price %>
  </div>
  <div class="field">
    <%= f.label :quot_id %><br>
    <%= f.text_field :quot_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotdetails/edit.html.erb
<h1>Editing quotdetail</h1>

<%= render 'form' %>

<%= link_to 'Show', @quotdetail %> |
<%= link_to 'Back', quotdetails_path %>

app/views/quotdetails/index.html.erb
<h1>Listing quotdetails</h1>

<table>
  <thead>
    <tr>
      <th>Quot number</th>
      <th>Product name</th>
      <th>Unit price</th>
      <th>Unit</th>
      <th>Quantity</th>
      <th>Extended price</th>
      <th>Quot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotdetails.each do |quotdetail| %>
      <tr>
        <td><%= quotdetail.quot_number %></td>
        <td><%= quotdetail.product_name %></td>
        <td><%= quotdetail.unit_price %></td>
        <td><%= quotdetail.unit %></td>
        <td><%= quotdetail.quantity %></td>
        <td><%= quotdetail.extended_price %></td>
        <td><%= quotdetail.quot %></td>
        <td><%= link_to 'Show', quotdetail %></td>
        <td><%= link_to 'Edit', edit_quotdetail_path(quotdetail) %></td>
        <td><%= link_to 'Destroy', quotdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quotdetail', new_quotdetail_path %>

app/views/quotdetails/new.html.erb
<h1>New quotdetail</h1>

<%= render 'form' %>

<%= link_to 'Back', quotdetails_path %>

app/views/quotdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quot number:</strong>
  <%= @quotdetail.quot_number %>
</p>

<p>
  <strong>Product name:</strong>
  <%= @quotdetail.product_name %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @quotdetail.unit_price %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @quotdetail.unit %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @quotdetail.quantity %>
</p>

<p>
  <strong>Extended price:</strong>
  <%= @quotdetail.extended_price %>
</p>

<p>
  <strong>Quot:</strong>
  <%= @quotdetail.quot %>
</p>

<%= link_to 'Edit', edit_quotdetail_path(@quotdetail) %> |
<%= link_to 'Back', quotdetails_path %>

app/views/quots/_form.html.erb
<%= form_for(@quot) do |f| %>
  <% if @quot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quot.errors.count, "error") %> prohibited this quot from being saved:</h2>

      <ul>
      <% @quot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quot_number %><br>
    <%= f.text_field :quot_number %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :representative %><br>
    <%= f.text_field :representative %>
  </div>
  <div class="field">
    <%= f.label :issued %><br>
    <%= f.date_select :issued %>
  </div>
  <div class="field">
    <%= f.label :consumption_tax %><br>
    <%= f.number_field :consumption_tax %>
  </div>
  <div class="field">
    <%= f.label :total_amount %><br>
    <%= f.number_field :total_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quots/edit.html.erb
<h1>Editing quot</h1>

<%= render 'form' %>

<%= link_to 'Show', @quot %> |
<%= link_to 'Back', quots_path %>

app/views/quots/index.html.erb
<h1>Listing quots</h1>

<table>
  <thead>
    <tr>
      <th>Quot number</th>
      <th>Customer</th>
      <th>Representative</th>
      <th>Issued</th>
      <th>Consumption tax</th>
      <th>Total amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quots.each do |quot| %>
      <tr>
        <td><%= quot.quot_number %></td>
        <td><%= quot.customer %></td>
        <td><%= quot.representative %></td>
        <td><%= quot.issued %></td>
        <td><%= quot.consumption_tax %></td>
        <td><%= quot.total_amount %></td>
        <td><%= link_to 'Show', quot %></td>
        <td><%= link_to 'Edit', edit_quot_path(quot) %></td>
        <td><%= link_to 'Destroy', quot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quot', new_quot_path %>

app/views/quots/new.html.erb
<h1>New quot</h1>

<%= render 'form' %>

<%= link_to 'Back', quots_path %>

app/views/quots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quot number:</strong>
  <%= @quot.quot_number %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quot.customer %>
</p>

<p>
  <strong>Representative:</strong>
  <%= @quot.representative %>
</p>

<p>
  <strong>Issued:</strong>
  <%= @quot.issued %>
</p>

<p>
  <strong>Consumption tax:</strong>
  <%= @quot.consumption_tax %>
</p>

<p>
  <strong>Total amount:</strong>
  <%= @quot.total_amount %>
</p>

<%= link_to 'Edit', edit_quot_path(@quot) %> |
<%= link_to 'Back', quots_path %>